### ISSUE TITLE
Possibility to control the layer index

### ISSUE THREAD

**Issue by xavijam** [Vizzuality/cartodb-leaflet#10]

**Comment by xavijam** [comment]
Waiting for this issue -> https://github.com/CloudMade/Leaflet/issues/505

**Comment by miceno** [comment]
Issue on layers is already solved in Leaflet -> https://github.com/CloudMade/Leaflet/issues/505

**Comment by xavijam** [comment]
It's closed but not really solved, because they didn't implement a layer position manager. They only provide two options, put it in back or in front. I will review their changes and try to improve them for the library. Thanks :)!
